# Generated by Django 4.0.3 on 2022-03-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('product_desc', models.TextField(max_length=1000)),
                ('product_price', models.FloatField()),
                ('product_discount_price', models.FloatField()),
                ('product_category', models.CharField(max_length=200)),
                ('product_image', models.CharField(max_length=300)),
            ],
        ),
    ]
